[package]
name = "kobold_todomvc_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kobold = { path = "../../crates/kobold" }
serde = { version = "1", features = ["derive"] }
gloo-storage = "0.2.1"

[dependencies.web-sys]
version = "0.3"
features = [
  "HtmlInputElement",
]
