[package]
name = "kobold_todomvc_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kobold = { path = "../../crates/kobold", version = "0.5.0" }
gloo-storage = "0.2.1"

[dependencies.web-sys]
version = "0.3"
features = [
  "HtmlInputElement",
]
