[workspace]
members = [
    "crates/kobold",
    "crates/kobold_macros",
    "examples/counter",
    "examples/hello_world",
    "examples/list",
    "examples/self_borrow",
]

[patch.crates-io]
kobold_macros = { path = "crates/kobold_macros" }

[profile.release]
lto = true

[profile.bench]
lto = "fat"
codegen-units = 1
