[package]
name = "kobold_qrcode_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kobold = { path = "../../crates/kobold" }
kobold_qr = { path = "../../crates/kobold_qr" }

[dependencies.web-sys]
version = "0.3"
features = [
  "HtmlInputElement",
]
