[package]
name = "kobold_qrcode_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kobold = "0.5"
kobold_qr = "0.5"

[dependencies.web-sys]
version = "0.3"
features = [
  "HtmlInputElement",
]
